use_frameworks!

target 'KRPresentationKit_Example' do
  pod 'KRAnimationKit'
  pod 'KRPresentationKit', :path => '../'

  # target 'KRPresentationKit_Tests' do
  #   inherit! :search_paths
  #   pod 'FBSnapshotTestCase'
  # end
end
