platform :ios, '8.0'
use_frameworks!

target 'KRPresentationKit_Example' do
  pod 'KRPresentationKit', :path => '../'
  
   target 'KRPresentationKit_Tests' do
     inherit! :search_paths
     pod 'KRPresentationKit', :path => '../'
   end
end
